### PR TITLE
Subscribe to render.compile

### PR DESCRIPTION
**Pull request by jpadilla**
Subscribe to `render.compile` instrument from https://github.com/emberjs/ember.js/pull/15085

cc: @paddyobrien @ghedamat

render-compile

### CODE REVIEW

**Comment by hjdivad** [comment]
👍 

seems like we'll want to update `package.json` to depend on the right version of ember-source after  https://github.com/emberjs/ember.js/pull/15085 is landed & released.

**Comment by hjdivad** [comment]
ah actually we probably don't need to do that; I imagine `subscribe` doesn't error for unknown events

**Comment by stefanpenner** [comment]
@jpadilla nice!

**Comment by stefanpenner** [comment]
fixing CI: https://github.com/stefanpenner/ember-perf-timeline/pull/12

**Comment by jpadilla** [comment]
@stefanpenner 🎉 thank you!

**Comment by stefanpenner** [comment]
released as v1.1.0

**Pull request merged**
